services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AuditBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Admin\AdminBundle\:
        resource: '%kernel.project_dir%/vendor/admin-pwe/adminbundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '%kernel.project_dir%/vendor/admin-pwe/adminbundle/{Entity,Repository,Tests}'

    Admin\AdminBundle\Controller\:
        resource: '%kernel.project_dir%/vendor/admin-pwe/adminbundle/Controller'
        public: true
        tags: ['controller.service_arguments']
